window.SISTEMA_THIAGO_OFFICIAL_SOURCES = [
  {
    id:'detran-sc',
    name:'DETRAN/SC — Leilões',
    agency:'Departamento Estadual de Trânsito de Santa Catarina',
    scope:'Santa Catarina',
    kind:'Leilões de veículos / editais',
    url:'https://www.detran.sc.gov.br/leiloes/',
    searchUrl:'https://www.detran.sc.gov.br/download-category/leiloes/',
    method:'Página e editais oficiais',
    status:'ATIVA',
    lastVerified:'2026-10-02'
  },
  {
    id:'compras-sc',
    name:'Portal de Compras SC',
    agency:'Governo do Estado de Santa Catarina',
    scope:'Santa Catarina',
    kind:'Processos de compras, alienações e leilões',
    url:'https://sistemas.sc.gov.br/sea/portaldecompras/',
    searchUrl:'https://sistemas.sc.gov.br/sea/portaldecompras/processos_publicados_portal.asp',
    method:'Portal oficial de processos publicados',
    lotsConnector:'pncp-detran',
    status:'ATIVA',
    lastVerified:'2026-10-02'
  },
  {
    id:'pncp',
    name:'PNCP',
    agency:'Portal Nacional de Contratações Públicas',
    scope:'Brasil',
    kind:'Editais e contratações públicas',
    url:'https://pncp.gov.br/',
    searchUrl:'https://pncp.gov.br/app/editais',
    method:'Portal oficial nacional',
    lotsConnector:'pncp',
    status:'ATIVA',
    lastVerified:'2026-10-02'
  },
  {
    id:'prf-sc',
    name:'PRF/SC — Leilões',
    agency:'Polícia Rodoviária Federal — Santa Catarina',
    scope:'Santa Catarina',
    kind:'Leilões de veículos recolhidos',
    url:'https://www.gov.br/prf/pt-br/assuntos/leiloes-prf/santa-catarina',
    searchUrl:'https://www.gov.br/prf/search?SearchableText=Leil%C3%A3o&origem=keyword',
    method:'Páginas e editais oficiais GOV.BR',
    lotsConnector:'prf-pdf',
    status:'ATIVA',
    lastVerified:'2026-10-02'
  },
  {
    id:'receita-federal',
    name:'Receita Federal — Leilões',
    agency:'Receita Federal do Brasil',
    scope:'Brasil',
    kind:'Mercadorias apreendidas ou abandonadas',
    url:'https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/leilao',
    searchUrl:'https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/leilao',
    method:'Sistema oficial de Leilão Eletrônico / e-CAC',
    status:'ATIVA',
    lastVerified:'2026-10-02'
  },
  {
    id:'florianopolis',
    name:'Prefeitura de Florianópolis — Licitações',
    agency:'Município de Florianópolis',
    scope:'Florianópolis/SC',
    kind:'Licitações e eventuais leilões municipais',
    url:'https://www.pmf.sc.gov.br/',
    searchUrl:'https://www.pmf.sc.gov.br/',
    method:'Portal oficial municipal',
    status:'MONITORAR',
    lastVerified:'2026-10-02'
  },
  {
    id:'sao-jose',
    name:'Prefeitura de São José — Publicações/Leilões',
    agency:'Município de São José',
    scope:'São José/SC',
    kind:'Publicações legais e leilões municipais',
    url:'https://saojose.sc.gov.br/',
    searchUrl:'https://saojose.sc.gov.br/',
    method:'Portal oficial municipal',
    status:'MONITORAR',
    lastVerified:'2026-10-02'
  },
  {
    id:'palhoca',
    name:'Prefeitura de Palhoça — Licitações',
    agency:'Município de Palhoça',
    scope:'Palhoça/SC',
    kind:'Licitações e eventuais leilões municipais',
    url:'https://palhoca.atende.net/',
    searchUrl:'https://palhoca.atende.net/',
    method:'Portal oficial municipal',
    status:'MONITORAR',
    lastVerified:'2026-10-02'
  },
  {
    id:'biguacu',
    name:'Prefeitura de Biguaçu',
    agency:'Município de Biguaçu',
    scope:'Biguaçu/SC',
    kind:'Publicações e licitações municipais',
    url:'https://www.biguacu.sc.gov.br/',
    searchUrl:'https://www.biguacu.sc.gov.br/',
    method:'Portal oficial municipal — localização específica a validar',
    status:'VALIDAR_ROTA',
    lastVerified:'2026-10-02'
  }
];

window.SISTEMA_THIAGO_OFFICIAL_RESULTS = [
  {
    id:'prf-sc-02-2026',
    sourceId:'prf-sc',
    sourceName:'PRF/SC — Leilões',
    agency:'Polícia Rodoviária Federal — Superintendência de Santa Catarina',
    title:'SC — Leilão 02/2026 — PRF/SC',
    reference:'Edital nº 30/2026/SPRF-SC',
    process:'',
    modality:'Leilão',
    criterion:'Maior lance',
    date:'2026-10-05',
    additionalDates:['2026-10-06','2026-10-07'],
    time:'',
    scope:'Santa Catarina',
    location:'On-line',
    platform:'Leiloeiro indicado no edital',
    object:'Venda de veículos de terceiros retidos, abandonados, removidos ou recolhidos há mais de 60 dias.',
    classifications:['Circulação','Sucata aproveitável com motor aproveitável','Sucata aproveitável com motor inservível','Sucata inservível'],
    officialUrl:'https://www.gov.br/prf/pt-br/assuntos/leiloes-prf/santa-catarina/sc-leilao-02-2026-prf-sc',
    foundAt:'gov.br/prf — página oficial PRF/SC',
    publishedAt:'2026-09-09',
    lastChecked:'2026-10-02',
    lotsConnector:'prf-pdf',
    extraFields:{
      'Data circulação':'05/10/2026',
      'Data sucata aproveitável':'06/10/2026',
      'Data sucata inservível':'07/10/2026'
    }
  },
  {
    id:'detran-sc-0013-2026',
    sourceId:'compras-sc',
    status:'NOVA DATA PUBLICADA',
    statusNote:'O DETRAN/SC publicou suspensão anterior e posteriormente um edital do Leilão 13/2026 com “NOVA DATA”. O Portal de Compras lista 13/10/2026 às 09:00; conferir o edital vigente antes do acompanhamento.',
    lotsConnector:'pncp-detran',
    pncp:{cnpj:'34060183000152',year:2026,sequence:40,control:'34060183000152-1-000040/2026'},
    detranDownloadPage:'https://www.detran.sc.gov.br/download/edital-descritivo-leilao-13-2026-blumenau-e-regioes-nova-data/',
    sourceName:'Portal de Compras SC',
    agency:'DETRAN/SC',
    title:'DETRAN/SC — Processo 0013/2026',
    reference:'Edital Descritivo do Leilão Público nº 13/DETRAN/2026',
    process:'0013/2026',
    modality:'Leilão Eletrônico',
    date:'2026-10-13',
    time:'09:00',
    scope:'Santa Catarina',
    object:'Veículos conservados e sucatas.',
    officialUrl:'https://sistemas.sc.gov.br/sea/portaldecompras/',
    foundAt:'Portal de Compras do Governo de Santa Catarina',
    lastChecked:'2026-10-02',
    extraFields:{}
  },
  {
    id:'detran-sc-1500-2026',
    sourceId:'compras-sc',
    status:'EM RECEBIMENTO DE PROPOSTA',
    lotsConnector:'pncp-detran',
    pncp:{cnpj:'34060183000152',year:2026,sequence:41,control:'34060183000152-1-000041/2026'},
    detranDownloadPage:'https://www.detran.sc.gov.br/download/edital-descritivo-do-leilao-publico-15-2026-fpolis-serra-e-regioes/',
    sourceName:'Portal de Compras SC',
    agency:'DETRAN/SC',
    title:'DETRAN/SC — Processo 1500/2026',
    reference:'Processo 1500/2026 — Portal de Compras SC',
    process:'1500/2026',
    modality:'Leilão Eletrônico',
    date:'2026-10-19',
    time:'12:32',
    scope:'Santa Catarina',
    object:'Alienação de veículos conservados e sucatas em pátios de custódia de municípios catarinenses.',
    officialUrl:'https://sistemas.sc.gov.br/sea/portaldecompras/',
    foundAt:'Portal de Compras do Governo de Santa Catarina',
    lastChecked:'2026-10-02',
    extraFields:{}
  },
  {
    id:'detran-sc-1600-2026',
    sourceId:'compras-sc',
    status:'EM RECEBIMENTO DE PROPOSTA',
    lotsConnector:'pncp-detran',
    pncp:{cnpj:'34060183000152',year:2026,sequence:44,control:'34060183000152-1-000044/2026'},
    detranDownloadPage:'https://www.detran.sc.gov.br/download/edital-descritivo-do-leilao-publico-16-2026-criciuma-e-outras-regioes/',
    sourceName:'Portal de Compras SC',
    agency:'DETRAN/SC',
    title:'DETRAN/SC — Processo 1600/2026',
    reference:'Processo 1600/2026 — Portal de Compras SC',
    process:'1600/2026',
    modality:'Leilão Eletrônico',
    date:'2026-10-26',
    time:'14:18',
    scope:'Santa Catarina',
    object:'Alienação de veículos conservados e sucatas em pátios de custódia de municípios catarinenses.',
    officialUrl:'https://sistemas.sc.gov.br/sea/portaldecompras/',
    foundAt:'Portal de Compras do Governo de Santa Catarina',
    lastChecked:'2026-10-02',
    extraFields:{}
  }
];
